### PR TITLE
Symfony 3 support

### PR DESCRIPTION
**Pull request by riskawarrior**
It looks that this bundle works perfectly with Symfony 3.
I've added it to Travis and to Composer config.

Are you going to merge the changes on develop into master in the near future? A new tag would be nice with the new Sf3 support.

### CODE REVIEW

**Comment by mreichstadt** [comment]
Hello,
I don't manage to make it work with sf3. How did you do?

**Comment by riskawarrior** [comment]
Did you use the code on develop branch? The master is pretty old, that's not woring with Sf3.

**Comment by mreichstadt** [comment]
No I didn't I'll try it thanks a lot

**Comment by mreichstadt** [comment]
YES!! perfect thank you!

**Comment by Maks3w** [comment]
V3 Released.

**Pull request closed without merging**
