### PR TITLE
[logger] Use placeholders instead sprintf

### PR DESCRIPTION
**Pull request by Maks3w**
Use PSR-3 placeholders and append additional data to context parameter.

### CODE REVIEW

**Comment by Maks3w** [comment]
I need someone to test this works as espected. Especially the exceptions logger part.

**Comment by snoob** [comment]
Ok i ll test

**Comment by Maks3w** [comment]
For to test exceptions are logged the most easy way is make the LDAP directory unreachable (change the ldap address in your config.yml)

**Comment by Maks3w** [comment]
@snoob Could you test this?

**Comment by snoob** [comment]
I'am on it ! Sorry i had no time

**Comment by snoob** [comment]
Nop it does'nt work [2015-05-04 21:09:06] ldap_driver.DEBUG: {action}({base_dn}, {filter}, {attributes}) {"action". I'll check why

**Comment by snoob** [comment]
Do you know the best way to enable PsrLogMessageProcessor ?

**Comment by Maks3w** [comment]
http://stackoverflow.com/questions/25305126/monolog-processors-not-working-with-symfony

**Comment by snoob** [comment]
I wrote this article but i thought i missed something (and it was native). Thank you !

**Comment by snoob** [comment]
The variable are not replaced in the log message. I don't know if it what you want ?

**Comment by Maks3w** [comment]
Do you find feasible write your own log processor for json encode the context?

**Comment by Maks3w** [comment]
In fact the log message is not required. $context contains all the information

**Comment by snoob** [comment]
True . I am trying the behavior with array

**Comment by snoob** [comment]
Ok it seems ok for me. We don't need to write our own log processor this one is perfect for array.

**Comment by snoob** [comment]
It would be better if variables was parsed in the message. I think i missed something

**Pull request merged**
