### PR TITLE
Added config option to enable/disable the ldap connection

### PR DESCRIPTION
**Pull request by felicitus**
Here's a pull request for #106.

This enables the user to disable the ldap connection if required.

### CODE REVIEW

**Comment by Maks3w** [comment]
If the user have to manual edit the config file for disable the plugin, Why not directly edit the security.yml.

**Comment by felicitus** [comment]
As described in https://github.com/Maks3w/FR3DLdapBundle/issues/106 where you mentioned that PRs are welcomed.

**Comment by Maks3w** [comment]
PR is incomplete (don't add tests) and the feature still not have sense after see the proposed implementation.

**Comment by felicitus** [comment]
The reason why this is not done in security.yml is because security.yml can't be overrridden. In my app, I generate a parameters.yml file when the user sets up the application. Remember that I'm not talking about a single symfony project which is deployed to a single site, I'm talking about a project which users will download and install on their box.

And simply because overwriting a security.yml on each upgrade will make custom changes in security.yml go away, that's the reason why this needs to be configurable.

As the feature works for me, and I don't see any reason why I should add unit tests if the feature makes no sense in your eyes, I'll use my fork for [PartKeepr](https://github.com/partkeepr/PartKeepr).

Have a nice day.

**Pull request closed without merging**
